name: Check code formatting with Prettier

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      - name: Check code formatting
        id: prettier
        run: npm run check-formatting
        continue-on-error: true

      - name: Check prettier failures
        if: steps.prettier.outcome != 'success'
        run: echo "::error::Code is not properly formatted with prettier" && exit 1