name: Format with Prettier

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Format code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,ts,vue}